version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-dev
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Password", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "4318:4318"    # OTLP HTTP receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - app-network

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      mssql:
        condition: service_healthy
      jaeger:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_PRIMARY_URL=jdbc:sqlserver://mssql:1433;databaseName=accounts_db;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_PRIMARY_USERNAME=sa
      - SPRING_DATASOURCE_PRIMARY_PASSWORD=YourStrong@Password
      - SPRING_DATASOURCE_SECONDARY_URL=jdbc:sqlserver://mssql:1433;databaseName=reporting_db;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_SECONDARY_USERNAME=sa
      - SPRING_DATASOURCE_SECONDARY_PASSWORD=YourStrong@Password
      - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://jaeger:4318/v1/traces
    networks:
      - app-network

volumes:
  mssql-data:

networks:
  app-network:
    driver: bridge